services:
  php_auth_authentication:
    container_name: php_auth_authentication
    build:
      context: .
      dockerfile: ./devops/php/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/var/www/html/auth-authentication:rw
      - /certificates:/certificates
      - ./devops/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./devops/php/php.ini-production:/usr/local/etc/php/php.ini-production